config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to tasks_path, notice: "登録しました"
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "編集しました！"
    else
      rendere :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"削除しました！"
  end

  private
  def task_params
    params.require(:task).permit(:name, :detail)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestManyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task_name">
    <%= form.label :task_name %>
    <%= form.text_field :name %>
  </div>
  <div class="task_detail">
    <%= form.label :task_detail%>
    <%= form.text_field :detail %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "戻る", tasks_path %>

app/views/tasks/edit.html.erb
<h1>編集タスク</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%= notice %></p>
<table>
  <head>
    <tr>
      <th>タスク名</th>
    </tr>
  </head>
  <body>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.detail %></td>
        <td><%= link_to '詳細',task_path(task.id) %></td>
        <td><%= link_to '編集',edit_task_path(task.id) %></td>
        <td><%= link_to '削除',task_path(task.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </body>
</table>
<br>
<%= link_to '追加', new_task_path %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>詳細画面</h1>
<p>タスク名: <%= @task.name %></p>
<p>タスク詳細: <%= @task.detail %></p>